# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/get_by_name?name=Sasha
Accept: application/json

###

GET http://127.0.0.1:8000/get_by_age?age=18
Accept: application/jsonpp